// GENERATED by scripts/build-board-images.sh — do not edit by hand.
// Source: gs://fathom-miles (private; these are the downscaled, committed copies).
//
// The slug IS the description — the bucket names each file for what it
// shows, which is what lets the matcher pick one from the list alone.

export const BOARD_IMAGES = [
  'ActionShotRoadCyclist',
  'ActionShotSurferInWave',
  'BackTwoSurfersRunningIntoOceanView',
  'BackWomanKayackingLake',
  'BikerOnCoastBeach',
  'BikersInField',
  'BirdsEyeViewDJPlayingMusic',
  'BirdsEyeViewGreenForest',
  'CloseUpDJSet',
  'CloseUpPointingToMap',
  'CloseUpRoadBike',
  'CoupleCuddlingDog',
  'CoupleHoldingSkateboardsBridge',
  'CoupleLaughing',
  'CoupleLookingAtMap',
  'DogHeadUpInField',
  'DogsHeadOutCarWindow',
  'GroupPeopleHikingSunrise',
  'HikerFieldBehindMountains',
  'HoldingPlantInPot',
  'InsideTentCamping',
  'KidLookingOverMomsShoulder',
  'KidOnManShouldersOnLake',
  'ManGardening',
  'ManHoldingChildsHandHike',
  'ManMovingBoxGuitarSoccerBallPlant',
  'ManSmilingAtDogInCar',
  'ManSmilingWithDogOnRock',
  'MistyForestPineShot',
  'MountainRangeView',
  'PeopleCampingOutside',
  'PeoplePlayingOnBeach',
  'PersonClimbingRock',
  'PersonJumpingRainbowOutside',
  'PersonKissingBaby',
  'SereneOceanView',
  'SideShotHiker',
  'Snowboarders',
  'TwoHappyDogsRunningField',
  'TwoHikersFromBehind',
  'TwoMenMovingCouch',
  'TwoPeopleDJing',
  'TwoPeopleKayacking',
  'TwoPeopleLaughingPaddlingOnKayack',
  'TwoRoadCyclistsInAction',
  'TwoSmilingFriendsKayacking',
  'TwoSurferGirlsOnBeach',
  'TwoSurfersRunningIntoWater',
  'TwoWomenMovingTable',
  'VanPersonInHammock',
  'ViewLakeInsideTent',
  'WideShotMountainRangeBlue',
  'WomanHoldingChildSmiling',
  'WomanHoldingPlantSmiling',
  'WomanOnPhoneWithCoffee',
  'WomanPlanterInGardenCenter',
  'WomanSmilingAtManInCar',
  'WomanWorkingWithManySmallPlants',
  'WomenInFieldSitting',
  'WomenLaptopOutside',
] as const;

export type BoardImage = (typeof BOARD_IMAGES)[number];

export const boardImageSrc = (slug: string) => `/board/${slug}.jpg`;

const VALID = new Set<string>(BOARD_IMAGES);
/** Guards against a model hallucinating a filename that has no file. */
export const isBoardImage = (s: unknown): s is BoardImage =>
  typeof s === 'string' && VALID.has(s);
