#!/usr/bin/env bash
# ── Bake the board photo set into public/board ──────────────────────────────
#
# The reveal board fills its tiles with photos from gs://fathom-miles. That
# bucket is private and the objects are ~600KB PNGs — far too heavy to drop into
# a 165x63 phone tile — so they are pulled once, downscaled, and committed.
#
# Re-run this whenever the bucket changes:
#   ./scripts/build-board-images.sh
#
# Requires: gcloud authenticated against the project that owns the bucket, and
# sips (ships with macOS). CLOUDSDK_PYTHON may need to point at a 3.10+ python.
set -euo pipefail

BUCKET="${BOARD_BUCKET:-gs://fathom-miles}"
OUT="public/board"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# 720 is the widest a tile ever renders: the full-width bubble is 240 design px,
# which is 336 CSS px on a 390 phone, or 672 device px at 2x. Width is pinned
# rather than the longest edge so a full-width tile never has to upscale.
WIDTH=720
QUALITY=80

echo "▶ Pulling $BUCKET …"
gcloud storage cp "$BUCKET/*" "$TMP/" >/dev/null 2>&1

mkdir -p "$OUT"
rm -f "$OUT"/*.jpg

count=0
for src in "$TMP"/*.png "$TMP"/*.jpg "$TMP"/*.jpeg; do
  [ -e "$src" ] || continue
  base="$(basename "$src")"
  slug="${base%.*}"
  sips -s format jpeg -s formatOptions "$QUALITY" \
       --resampleWidth "$WIDTH" "$src" --out "$OUT/$slug.jpg" >/dev/null
  count=$((count + 1))
done

echo "▶ Wrote $count images to $OUT"
du -sh "$OUT"

# The manifest is generated, not hand-kept, so the model can never be offered a
# slug that has no file behind it.
MANIFEST="app/lib/boardImages.ts"
{
  echo "// GENERATED by scripts/build-board-images.sh — do not edit by hand."
  echo "// Source: $BUCKET (private; these are the downscaled, committed copies)."
  echo "//"
  echo "// The slug IS the description — the bucket names each file for what it"
  echo "// shows, which is what lets the matcher pick one from the list alone."
  echo ""
  echo "export const BOARD_IMAGES = ["
  for f in "$OUT"/*.jpg; do
    echo "  '$(basename "${f%.jpg}")',"
  done
  echo "] as const;"
  echo ""
  echo "export type BoardImage = (typeof BOARD_IMAGES)[number];"
  echo ""
  echo "export const boardImageSrc = (slug: string) => \`/board/\${slug}.jpg\`;"
  echo ""
  echo "const VALID = new Set<string>(BOARD_IMAGES);"
  echo "/** Guards against a model hallucinating a filename that has no file. */"
  echo "export const isBoardImage = (s: unknown): s is BoardImage =>"
  echo "  typeof s === 'string' && VALID.has(s);"
} > "$MANIFEST"

echo "▶ Wrote $MANIFEST"
